# Databricks notebook source
# MAGIC %md
# MAGIC # AI Parts Wizard — Schema & Table Creation (Phase 1)
# MAGIC
# MAGIC Creates the `ai_parts_wizard` schema and the Delta data model in an existing
# MAGIC catalog (passed as the `catalog` job parameter; no catalog-create permission needed).
# MAGIC Medallion layers are table-name prefixes (`silver_` master, `gold_` serving). See spec §3.
# MAGIC
# MAGIC Idempotent: drops and recreates the tables (data is regenerated by the generation notebook).

# COMMAND ----------

# Target location — passed as job parameters (see DEPLOY.md).
dbutils.widgets.text("catalog", "")
dbutils.widgets.text("schema", "ai_parts_wizard")
CATALOG = dbutils.widgets.get("catalog")
SCHEMA = dbutils.widgets.get("schema")
assert CATALOG, "catalog is a required job parameter"
FQ = f"{CATALOG}.{SCHEMA}"

spark.sql(
    f"CREATE SCHEMA IF NOT EXISTS {FQ} "
    "COMMENT 'AI Parts Wizard — part standardization & component rationalization engine "
    "(github.com/weberdla/dbx-ai-parts-wizard)'"
)
print("schema ready:", FQ)

# COMMAND ----------

# MAGIC %md ## Drop existing tables (dependency order, idempotent)

# COMMAND ----------

for t in [
    "silver_supplier_catalogs", "gold_ground_truth", "silver_parts",
    "gold_normalized_parts", "silver_models", "silver_suppliers", "silver_plants",
]:
    spark.sql(f"DROP TABLE IF EXISTS {FQ}.{t}")
print("dropped existing tables")

# COMMAND ----------

# MAGIC %md ## silver_plants

# COMMAND ----------

spark.sql(f"""
CREATE TABLE {FQ}.silver_plants (
  plant_id      STRING NOT NULL COMMENT 'Opaque surrogate PK',
  plant_name    STRING,
  location      STRING,
  machine_focus STRING COMMENT 'tractor | harvester | both',
  CONSTRAINT pk_silver_plants PRIMARY KEY (plant_id)
) USING DELTA
COMMENT 'Design/manufacturing centers (4). Spec 3.1-3.2.'
""")

# COMMAND ----------

# MAGIC %md ## silver_models  (Plant -> Model)

# COMMAND ----------

spark.sql(f"""
CREATE TABLE {FQ}.silver_models (
  model_id     STRING NOT NULL COMMENT 'Opaque surrogate PK',
  plant_id     STRING NOT NULL COMMENT 'FK -> silver_plants',
  machine_type STRING NOT NULL COMMENT 'Harvester | Tractor',
  model_name   STRING,
  CONSTRAINT pk_silver_models PRIMARY KEY (model_id),
  CONSTRAINT fk_silver_models_plant FOREIGN KEY (plant_id) REFERENCES {FQ}.silver_plants(plant_id)
) USING DELTA
COMMENT 'Machine models/designs. Model versions are distinct model_ids. Spec 3.1-3.2.'
""")

# COMMAND ----------

# MAGIC %md ## gold_normalized_parts  (assigned during review; created before parts for the FK)

# COMMAND ----------

spark.sql(f"""
CREATE TABLE {FQ}.gold_normalized_parts (
  normalized_part_id     STRING NOT NULL COMMENT 'Opaque surrogate PK',
  enterprise_part_number STRING COMMENT 'Canonical enterprise part number for a rationalized cluster',
  part_category          STRING,
  assigned_by            STRING,
  assigned_at            TIMESTAMP,
  notes                  STRING,
  CONSTRAINT pk_gold_normalized_parts PRIMARY KEY (normalized_part_id)
) USING DELTA
COMMENT 'Normalized enterprise part numbers (side-by-side identity, assigned in review). Spec 3.1, 3.3.'
""")

# COMMAND ----------

# MAGIC %md ## silver_parts  (wide table; nullable per-category columns; `description` added)
# MAGIC part_number is unique WITHIN a model only -> never join/group on it alone (spec 3.1).
# MAGIC part_category & material are hard blocking keys (NOT NULL) per spec 9.2.

# COMMAND ----------

spark.sql(f"""
CREATE TABLE {FQ}.silver_parts (
  part_id            STRING NOT NULL COMMENT 'Opaque surrogate PK, stable across pipeline reruns',
  model_id           STRING NOT NULL COMMENT 'FK -> silver_models (plant derived via model)',
  part_number        STRING NOT NULL COMMENT 'Local/original number, unique within model only',
  part_category      STRING NOT NULL COMMENT 'Blocking key: one of the 8 categories (spec 3.2.1)',
  material           STRING NOT NULL COMMENT 'Blocking key',
  material_density   DOUBLE COMMENT 'Universal feature',
  weight             DOUBLE COMMENT 'Universal feature',
  description        STRING COMMENT 'Human-readable summary (display & Genie only; not a matching feature)',
  length             DOUBLE,
  width              DOUBLE,
  thickness          DOUBLE,
  diameter           DOUBLE,
  inner_diameter     DOUBLE,
  outer_diameter     DOUBLE,
  nominal_diameter   DOUBLE,
  cross_section_diameter DOUBLE,
  head_width         DOUBLE,
  gauge              DOUBLE,
  thread_pitch       DOUBLE,
  tensile_strength   DOUBLE,
  hardness           DOUBLE,
  pressure_rating    DOUBLE,
  load_rating        DOUBLE,
  temperature_rating DOUBLE,
  hole_count         INT,
  voltage_rating     DOUBLE,
  conductor_count    INT,
  normalized_part_id STRING COMMENT 'FK -> gold_normalized_parts, NULL until rationalized',
  annual_volume      INT COMMENT 'Units purchased per year for this part (synthetic); drives spend and savings',
  CONSTRAINT pk_silver_parts PRIMARY KEY (part_id),
  CONSTRAINT fk_silver_parts_model FOREIGN KEY (model_id) REFERENCES {FQ}.silver_models(model_id),
  CONSTRAINT fk_silver_parts_normalized FOREIGN KEY (normalized_part_id) REFERENCES {FQ}.gold_normalized_parts(normalized_part_id)
) USING DELTA
COMMENT 'Parts (~200K). Wide table with nullable per-category columns. Spec 3.1-3.2.1.'
""")

# COMMAND ----------

# MAGIC %md ## silver_suppliers

# COMMAND ----------

spark.sql(f"""
CREATE TABLE {FQ}.silver_suppliers (
  supplier_id   STRING NOT NULL COMMENT 'Opaque surrogate PK',
  supplier_name STRING,
  region        STRING,
  CONSTRAINT pk_silver_suppliers PRIMARY KEY (supplier_id)
) USING DELTA
COMMENT 'Suppliers (100s). Spec 3.2.'
""")

# COMMAND ----------

# MAGIC %md ## silver_supplier_catalogs

# COMMAND ----------

spark.sql(f"""
CREATE TABLE {FQ}.silver_supplier_catalogs (
  supplier_id            STRING NOT NULL COMMENT 'FK -> silver_suppliers',
  part_id                STRING NOT NULL COMMENT 'FK -> silver_parts',
  price_per_unit         DOUBLE,
  unit_discount          DOUBLE,
  lead_time_days         INT,
  currency               STRING COMMENT 'ISO 4217 code (demo data: USD)',
  material_quality_grade STRING,
  CONSTRAINT pk_silver_supplier_catalogs PRIMARY KEY (supplier_id, part_id),
  CONSTRAINT fk_ssc_supplier FOREIGN KEY (supplier_id) REFERENCES {FQ}.silver_suppliers(supplier_id),
  CONSTRAINT fk_ssc_part FOREIGN KEY (part_id) REFERENCES {FQ}.silver_parts(part_id)
) USING DELTA
COMMENT 'Supplier pricing/lead-time per part. Spec 3.2.'
""")

# COMMAND ----------

# MAGIC %md ## gold_ground_truth  (seeded relationships for evaluation)

# COMMAND ----------

spark.sql(f"""
CREATE TABLE {FQ}.gold_ground_truth (
  base_part_id    STRING NOT NULL COMMENT 'FK -> silver_parts (the original)',
  variant_part_id STRING NOT NULL COMMENT 'FK -> silver_parts (the seeded variant)',
  relationship    STRING NOT NULL COMMENT 'duplicate | hard_negative | near_miss',
  part_category   STRING,
  CONSTRAINT pk_gold_ground_truth PRIMARY KEY (variant_part_id)
) USING DELTA
COMMENT 'Seeded ground-truth relationships for matching evaluation. Spec 4, 9.5.'
""")

# COMMAND ----------

display(spark.sql(f"SHOW TABLES IN {FQ}"))
